name:                kitty
version:             0.0.2.0
git:                 "https://gitlab.com/metaporia/kitty"
license:             MIT
author:              "Keane YahnKrafft"
maintainer:          "kyahnkrafft@me.com"
copyright:           "2019 Keane Yahn-Krafft"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitLab at <https://gitlab.com/metaporia/kitty#readme>

dependencies:
- base >= 4.7 && < 5
- trifecta
- pretty-show
- raw-strings-qq
- parsers
- optparse-applicative
- containers
- matrix
- boxes

library:
  source-dirs: src
  ghc-options:
    - -Wall 
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wpartial-fields
    - -WredundantConstraints
    - -WMiss
    - -fno-warn-name-shadowing
    - -fno-warn-type-defaults
  exposed-modules:
    - Lib

executables:
  tallyKitty:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kitty

tests:
  kitty-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kitty
