name:                kitty
version:             0.0.2.0
github:              "githubuser/kitty"
license:             BSD3
author:              "Keane YahnKrafft"
maintainer:          "kyahnkrafft@me.com"
copyright:           "2018 Keane Yahn-Krafft"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/kitty#readme>

dependencies:
- base >= 4.7 && < 5
- trifecta
- pretty-show
- raw-strings-qq
- parsers
- optparse-applicative
- containers
- matrix
- boxes

library:
  source-dirs: src
  exposed-modules:
    - Lib

executables:
  tallyKitty:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kitty

tests:
  kitty-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kitty
